import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../App';
import { MOCK_USERS_LIST } from '../constants';
import { UserRole, User } from '../types';
import { GlassCard, GlassButton, GlassInput, FloatingSphere } from '../components/ui';

import { useGoogleLogin } from '@react-oauth/google';

// Use environment variable or default to local development port
const API_BASE = import.meta.env.VITE_API_URL || '/api/opas';

const Login: React.FC = () => {
  const [userId, setUserId] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [isGoogleLoading, setIsGoogleLoading] = useState(false);
  const { login } = useAuth();
  const navigate = useNavigate();

  /**
   * Attempt to log in via our new MongoDB Atlas/Node.js backend first.
   */
  const loginViaBackend = async (email: string, name: string, avatar: string): Promise<User | null> => {
    try {
      const res = await fetch(`${API_BASE}/auth/login`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email, name, avatar }),
      });
      
      if (res.ok) {
        const data = await res.json();
        // Backend returns user in the shape defined in server.js formatUser()
        return data as User;
      }
      return null;
    } catch (_err) {
      console.warn('Backend not reachable, falling back to localStorage demo mode.');
      return null;
    }
  };

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);
    setError('');

    const normalizedId = userId.trim().toLowerCase();

    // ─── 1. Attempt Cloud Auth ───────────────────
    const bUser = await loginViaBackend(normalizedId, '', '');
    if (bUser) {
      login(bUser);
      navigate('/');
      return;
    }

    // ─── 2. Fallback to Local Storage/Shortcodes ─────────────────────
    setTimeout(() => {
      let foundUser = null;
      const allUsers = JSON.parse(localStorage.getItem('opas_users') || JSON.stringify(MOCK_USERS_LIST));

      // Handle role-based testing shortcodes
      const shortcodeRoleMap: Record<string, UserRole> = {
        'student': UserRole.STUDENT,
        'mentor': UserRole.FACULTY,
        'faculty': UserRole.FACULTY,
        'parent': UserRole.PARENT,
        'hod': UserRole.HOD,
        'warden': UserRole.WARDEN,
        'admin': UserRole.ADMIN
      };

      if (shortcodeRoleMap[normalizedId]) {
        foundUser = allUsers.find((u: any) => u.roles.includes(shortcodeRoleMap[normalizedId]));
      } else {
        foundUser = allUsers.find((u: any) => 
          u.id.toLowerCase() === normalizedId || 
          u.email.toLowerCase() === normalizedId
        );
      }

      if (foundUser && (password === 'password' || password === 'Apple!@#$0987')) {
        login(foundUser);
        navigate('/');
      } else {
        setError('Invalid credentials. If you are new, try Continue with Google.');
        setIsLoading(false);
      }
    }, 800);
  };

  const loginWithGoogle = useGoogleLogin({
    onSuccess: async (tokenResponse) => {
      setIsGoogleLoading(true);
      setError('');
      try {
        const res = await fetch('https://www.googleapis.com/oauth2/v3/userinfo', {
          headers: { Authorization: `Bearer ${tokenResponse.access_token}` },
        });
        const googleUser = await res.json();
        
        if (googleUser.email) {
          // --- Always sync with cloud backend (MongoDB) ---
          const bUser = await loginViaBackend(
            googleUser.email,
            googleUser.name || 'New User',
            googleUser.picture || ''
          );

          if (bUser) {
            login(bUser);
            navigate('/');
          } else {
            // Fallback to localStorage logic if server is offline
            const allUsers = JSON.parse(localStorage.getItem('opas_users') || JSON.stringify(MOCK_USERS_LIST));
            const foundUser = allUsers.find((u: any) => u.email.toLowerCase() === googleUser.email.toLowerCase());
            if (foundUser) {
                login(foundUser);
                navigate('/');
            } else {
                 const autoGenerated = {
                   id: Math.floor(100000 + Math.random() * 900000).toString(),
                   name: googleUser.name || 'New User',
                   email: googleUser.email,
                   roles: [UserRole.STUDENT],
                   avatar: googleUser.picture,
                   department: 'Computer Science',
                   status: 'ACTIVE'
                 };
                 allUsers.push(autoGenerated);
                 localStorage.setItem('opas_users', JSON.stringify(allUsers));
                 login(autoGenerated as any);
                 navigate('/');
            }
          }
        }
      } catch (err) {
        setError('Failed to authenticate with Google.');
        setIsGoogleLoading(false);
      }
    },
    onError: () => {
      setError('Google Login was canceled or failed.');
    }
  });

  return (
    <div className="min-h-screen flex items-center justify-center relative overflow-hidden bg-[#e8e5df] font-sans">
      <div className="fixed inset-0 pointer-events-none overflow-hidden z-0">
         <div className="absolute top-[-15%] left-[-5%] w-[50%] h-[50%] bg-purple-400/40 rounded-full blur-[120px]" />
         <div className="absolute bottom-[-10%] right-[-8%] w-[55%] h-[55%] bg-indigo-500/30 rounded-full blur-[120px]" />
         <div className="absolute top-[40%] right-[20%] w-[30%] h-[30%] bg-cyan-400/25 rounded-full blur-[100px]" />
         <div className="absolute bottom-[20%] left-[10%] w-[25%] h-[25%] bg-pink-300/20 rounded-full blur-[100px]" />
      </div>

      <FloatingSphere size={200} color="bg-indigo-400" delay={0} className="-top-12 -left-12" />
      <FloatingSphere size={120} color="bg-cyan-400" delay={2} className="bottom-20 right-20" />
      <FloatingSphere size={80} color="bg-purple-400" delay={4} className="top-40 right-40" />

      <div className="w-full max-w-md p-6 relative z-10 animate-in zoom-in-95 duration-700">
        <GlassCard variant="light" className="p-8 md:p-10 text-center relative overflow-visible">
          <div className="flex justify-center mb-6">
            <div className="w-20 h-20 bg-gradient-to-br from-indigo-500 to-purple-600 rounded-[1.5rem] flex items-center justify-center text-white text-4xl font-black shadow-[0_10px_30px_rgba(99,102,241,0.4)] border-4 border-[#f4f3ef]/50 backdrop-blur-md">
              O
            </div>
          </div>
          
          <div className="mb-6">
            <h1 className="text-3xl font-extrabold tracking-tight text-slate-800">OPAS Workspace</h1>
            <p className="text-sm text-slate-500 font-medium mt-2">Premium Operating Interface (Cloud Backend Connected)</p>
          </div>

          <form onSubmit={handleLogin} className="space-y-4 text-left mb-6">
            
            <div className="space-y-2">
              <label className="text-xs font-bold text-slate-500 uppercase tracking-widest pl-2">System Identity</label>
              <GlassInput
                type="text"
                placeholder="e.g. student@opas.edu or 108422"
                icon={<span>👤</span>}
                required
                value={userId}
                onChange={(e) => setUserId(e.target.value)}
              />
            </div>

            <div className="space-y-2">
              <label className="text-xs font-bold text-slate-500 uppercase tracking-widest pl-2">Security Code</label>
              <GlassInput
                type="password"
                placeholder="••••••••"
                icon={<span>🔒</span>}
                required
                value={password}
                onChange={(e) => setPassword(e.target.value)}
              />
            </div>

            {error && (
              <div className="bg-red-500/10 text-rose-600 p-3 rounded-xl text-xs font-bold border border-red-500/20 backdrop-blur-md animate-shake">
                {error}
              </div>
            )}

            <GlassButton 
              type="submit"
              variant="primary"
              size="lg"
              className="w-full mt-2"
              disabled={isLoading || isGoogleLoading}
            >
              {isLoading ? (
                <>
                  <span className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin mr-3"></span>
                  Connecting...
                </>
              ) : 'Sign in'}
            </GlassButton>
          </form>

          <div className="relative flex py-2 items-center mb-6">
            <div className="flex-grow border-t border-slate-300"></div>
            <span className="flex-shrink-0 mx-4 text-slate-400 text-xs font-bold uppercase tracking-wider">or continue with</span>
            <div className="flex-grow border-t border-slate-300"></div>
          </div>

          <GlassButton 
            type="button"
            variant="secondary"
            size="lg"
            className="w-full bg-white/50 hover:bg-white/80"
            onClick={() => loginWithGoogle()}
            disabled={isLoading || isGoogleLoading}
          >
            {isGoogleLoading ? (
               <span className="w-5 h-5 border-2 border-slate-400 border-t-slate-800 rounded-full animate-spin mr-3"></span>
            ) : (
               <svg className="w-5 h-5 mr-3" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><g clipPath="url(#clip0_32_4705)"><path d="M23.7659 12.2741C23.7659 11.4601 23.6999 10.6391 23.5579 9.83911H12.2399V14.4581H18.7209C18.4379 15.9381 17.5879 17.2681 16.3269 18.1041V21.0961H20.1899C22.4609 19.0061 23.7659 15.9261 23.7659 12.2741Z" fill="#4285F4"/><path d="M12.2403 23.9998C15.4853 23.9998 18.2083 22.9378 20.1903 21.0958L16.3273 18.1038C15.2533 18.8328 13.8633 19.2518 12.2403 19.2518C9.11234 19.2518 6.45834 17.1398 5.50634 14.3008H1.51538V17.3918C3.55238 21.4428 7.69734 23.9998 12.2403 23.9998Z" fill="#34A853"/><path d="M5.50153 14.2996C5.00853 12.8256 5.00853 11.1736 5.50153 9.69961V6.60861H1.51553C-0.186469 10.0046 -0.186469 13.9946 1.51553 17.3906L5.50153 14.2996Z" fill="#FBBC05"/><path d="M12.2403 4.74766C13.9573 4.72266 15.6023 5.36566 16.8423 6.54766L20.2683 3.12166C18.1013 1.08266 15.2213 -0.0353412 12.2403 0.000658826C7.69734 0.000658826 3.55238 2.55666 1.51538 6.60766L5.50038 9.69866C6.45138 6.85266 9.10834 4.74766 12.2403 4.74766Z" fill="#EA4335"/></g><defs><clipPath id="clip0_32_4705"><rect width="24" height="24" fill="white"/></clipPath></defs></svg>
            )}
            Continue with Google
          </GlassButton>

          <div className="mt-8 grid grid-cols-3 gap-2 text-center text-[10px] font-bold uppercase tracking-tighter">
             {['student', 'faculty', 'parent', 'hod', 'warden', 'admin'].map(r => (
               <div key={r} className="bg-white/30 p-2 rounded-lg border border-white/50 text-indigo-900/60 shadow-sm">{r}</div>
             ))}
          </div>
        </GlassCard>
      </div>

      <style>{`
        @keyframes shake {
          0%, 100% { transform: translateX(0); }
          25% { transform: translateX(-5px); }
          75% { transform: translateX(5px); }
        }
        .animate-shake { animation: shake 0.2s ease-in-out 0s 2; }
      `}
      </style>
    </div>
  );
};

export default Login;
